# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('birthday', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('skype', models.CharField(max_length=256)),
                ('jabber', models.CharField(max_length=256)),
                ('other', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
